version: "3"
services:
  minio:
    image: "minio/minio"
    expose:
      - "9000"
    ports:
      - "9000:9000"
    command: server /data

  screenshot:
    depends_on:
      - minio
    build:
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - PORT=8080
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    ports:
      - "8080:8080"
